# -*- coding: utf-8 -*-
"""Data_Cleaning_time_date_in_str.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14E_TUDKlHh1hF0Ndxj_mi2mUz6AwhYpL

**Uploading input file for further cleaning**
"""

import pandas as pd
df = pd.read_csv('input_file.csv',header = None)
df

"""Splitting column (separating time/date from kwh) """

for i in range(1,9):
    str = f'df[0] = df[0].str.replace("{i}_","{i}@")'
    exec(str)
    i =+1
df[[0,1]] = df[0].str.split('@',expand=True)
df

"""Trimming and removing "_" in string"""

df[0] = df[0].str.replace("_","")
df[0] = df[0].str.strip()
df

"""**Formatting time inside string**"""

df[0] = df[0].str.replace(" pm","pm")
df[0] = df[0].str.replace(" Pm","pm")
df[0] = df[0].str.replace(" PM","pm")
df[0] = df[0].str.replace("PM","pm")
df[0] = df[0].str.replace("Pm","pm")
df[0] = df[0].str.replace(" am","am")
df[0] = df[0].str.replace(" Am","am")
df[0] = df[0].str.replace(" AM","am")
df[0] = df[0].str.replace("AM","am")
df[0] = df[0].str.replace("Am","am")
df

"""**Formatting date**"""

df[0] = df[0].str.replace("st-","-")
df[0] = df[0].str.replace("nd-","-")
df[0] = df[0].str.replace("rd-","-")
df[0] = df[0].str.replace("th-","-")
df

"""**Separating time string from rest of the string**"""

df[0] = df[0].str.replace("m ","m *")
df[[0,2]] = df[0].str.split('*', expand = True)
df[0] = df[0].str.rstrip() #removes any trailing characters (​characters at the end a string),
                           # space is the default trailing character to remove
df

"""**Extracting date from string**"""

df[2] = df[2].str[-11:]
df

"""**Reordering / renaming columns and adding new datetime column**"""

df = df[[0,2,1]]
df.rename(columns={0:"Time", 2:"Date", 1:"kwh"}, inplace=True)
df["Datetime"] = pd.to_datetime(df['Date'] + ' ' + df['Time'], exact=True)
df

"""**Changing data type for kwh column**"""

df["kwh"] = df["kwh"].str.replace("_","")
df["kwh"] = df["kwh"].str.replace(" kwh","")
df["kwh"] = df["kwh"].str.replace("kwh","")
df["kwh"] = df["kwh"].astype(float)
df

"""**Removing necessary columns**"""

df = df[["Datetime","kwh"]]
df